// This file is automatically generated, please do not touch

package slime.base.proto.autogen;


import slime.base.proto.SByteBuffer;
import slime.base.proto.types.*;
import slime.base.proto.autogen.*;
import slime.base.proto.Util;
import java.util.UUID;

/// Constant values, including enums
public class Consts {
	/**  Value of SlimeHandshakeInit.magic_int */
	public static final long SLIME_HANDSHAKE_INIT_INT = 3265741128L;
	/**  Value of SlimeHandshakeInit.magic_short */
	public static final long SLIME_HANDSHAKE_INIT_SHORT = 11359L;
	/**  Value of SlimeHandshakeInit.magic_byte */
	public static final long SLIME_HANDSHAKE_INIT_BYTE = 181L;
	/**  Value of SlimeHandshakeInit.magic_uuid (92b40922-445e-4484-bc3d-f0c696a3080c) */
	public static final UUID SLIME_HANDSHAKE_INIT_UUID = UUID.fromString("92b40922-445e-4484-bc3d-f0c696a3080c");
	/**  Value of SlimeHandshakeInitResponse.magic */
	public static final long SLIME_HANDSHAKE_RESPONSE_MAGIC = 1029226168L;
	/**  `SlimeHandshakeInitResponse` contained invalid magic values. */
	public static final UUID SLIME_ERROR_INVALID_INIT_RESPONSE = UUID.fromString("10000001-445e-4484-bc3d-f0c696a3080c");
	/**  A command was received with an invalid handle. */
	public static final UUID SLIME_ERROR_INVALID_HANDLE = UUID.fromString("10000002-445e-4484-bc3d-f0c696a3080c");


	/** Enum value part of SlimeReservedHandle */
	public static final int SLIME_HANDLE_HANDSHAKE_INIT = 1;
	/** Enum value part of SlimeReservedHandle */
	public static final int SLIME_HANDLE_HANDSHAKE_INIT_R = 2;
	/** Enum value part of SlimeReservedHandle */
	public static final int SLIME_HANDLE_HANDSHAKE = 3;
	/** Enum value part of SlimeReservedHandle */
	public static final int SLIME_HANDLE_HANDSHAKE_R = 4;
	/** Enum value part of SlimeReservedHandle */
	public static final int SLIME_HANDLE_CMD_DESC = 5;
	/** Enum value part of SlimeReservedHandle */
	public static final int SLIME_HANDLE_CMD_DESC_R = 6;
	/** Enum value part of SlimeReservedHandle */
	public static final int SLIME_HANDLE_PACKET_ACK = 7;
	/** Enum value part of SlimeReservedHandle */
	public static final int SLIME_HANDLE_REPORT_ERROR = 8;
	/** Enum value part of SlimeReservedHandle */
	public static final int SLIME_HANDLE_FINALIZE_DESCRIPTORS = 9;
	/** Enum value part of SlimeReservedHandle */
	public static final int SLIME_HANDLE_RESET_REQUEST = 10;


	/** Enum value part of SlimeReliabilityBits */
	public static final int SLIME_RELIABILITY_ACK = 1;
	/** Enum value part of SlimeReliabilityBits */
	public static final int SLIME_RELIABILITY_ORDERING = 2;


	/** Enum value part of SlimeCommandFlagBits */
	public static final int SLIME_COMMAND_CLIENT_SENDS = 1;
	/** Enum value part of SlimeCommandFlagBits */
	public static final int SLIME_COMMAND_SERVER_SENDS = 2;
	/** Enum value part of SlimeCommandFlagBits */
	public static final int SLIME_COMMAND_ORDERED = 4;
	/** Enum value part of SlimeCommandFlagBits */
	public static final int SLIME_COMMAND_ACKNOWLEDGE = 8;


	/** Enum value part of SlimeCommandDescriptorStatus */
	public static final int SLIME_COMMAND_ACK_ERROR = 0;
	/** Enum value part of SlimeCommandDescriptorStatus */
	public static final int SLIME_COMMAND_ACK_OK = 1;
	/** Enum value part of SlimeCommandDescriptorStatus */
	public static final int SLIME_COMMAND_ACK_UNKNOWN = 2;


	/** Enum value part of SlimeResetRequestType */
	public static final int SLIME_RESET_REQUEST_RETRY_HANDSHAKE = 1;
	/** Enum value part of SlimeResetRequestType */
	public static final int SLIME_RESET_REQUEST_REBOOT = 2;

}
