// This file is automatically generated, please do not touch

package slime.base.proto.autogen;


import slime.base.proto.SByteBuffer;
import slime.base.proto.types.*;
import slime.base.proto.autogen.*;
import slime.base.proto.Util;
import java.util.UUID;

/// Constant values, including enums
public class Consts {
	/**  Value of SlimeHandshakeInit.magic_int */
	public static final long SLIME_HANDSHAKE_INIT_INT = 3265741128L;
	/**  Value of SlimeHandshakeInit.magic_short */
	public static final long SLIME_HANDSHAKE_INIT_SHORT = 11359L;
	/**  Value of SlimeHandshakeInit.magic_byte */
	public static final long SLIME_HANDSHAKE_INIT_BYTE = 181L;
	/**  Value of SlimeHandshakeInit.magic_uuid (92b40922-095c-4e37-9a42-f24d73ee3ae9) */
	public static final UUID SLIME_HANDSHAKE_INIT_UUID = UUID.fromString("92b40922-095c-4e37-9a42-f24d73ee3ae9");
	/**  Value of SlimeHandshakeResponse.magic */
	public static final long SLIME_HANDSHAKE_RESPONSE_MAGIC = 1029226168L;


	/** Enum value part of SlimeReservedHandle */
	public static final int SLIME_HANDLE_HANDSHAKE_INIT = 1;
	/** Enum value part of SlimeReservedHandle */
	public static final int SLIME_HANDLE_HANDSHAKE = 2;
	/** Enum value part of SlimeReservedHandle */
	public static final int SLIME_HANDLE_HANDSHAKE_R = 3;
	/** Enum value part of SlimeReservedHandle */
	public static final int SLIME_HANDLE_CMD_DESC = 4;
	/** Enum value part of SlimeReservedHandle */
	public static final int SLIME_HANDLE_CMD_DESC_R = 5;
	/** Enum value part of SlimeReservedHandle */
	public static final int SLIME_HANDLE_PACKET_ACK = 6;


	/** Enum value part of SlimeReliabilityBits */
	public static final int SLIME_RELIABILITY_ACK = 1;
	/** Enum value part of SlimeReliabilityBits */
	public static final int SLIME_RELIABILITY_ORDERING = 2;


	/** Enum value part of SlimeCommandFlagBits */
	public static final int SLIME_COMMAND_CLIENT_SENDS = 1;
	/** Enum value part of SlimeCommandFlagBits */
	public static final int SLIME_COMMAND_SERVER_SENDS = 2;
	/** Enum value part of SlimeCommandFlagBits */
	public static final int SLIME_COMMAND_ORDERED = 4;
	/** Enum value part of SlimeCommandFlagBits */
	public static final int SLIME_COMMAND_ACKNOWLEDGE = 8;


	/** Enum value part of SlimeCommandDescriptorStatus */
	public static final int SLIME_COMMAND_ACK_ERROR = 0;
	/** Enum value part of SlimeCommandDescriptorStatus */
	public static final int SLIME_COMMAND_ACK_OK = 1;
	/** Enum value part of SlimeCommandDescriptorStatus */
	public static final int SLIME_COMMAND_ACK_UNKNOWN = 2;

}
