// This file is automatically generated, please do not touch

package slime.base.proto.autogen;


import slime.base.proto.SByteBuffer;
import slime.base.proto.types.*;
import slime.base.proto.autogen.*;
import slime.base.proto.Util;
import java.util.UUID;

/**  If an error has occurred, the tracker may report it to the server using this command. Depending on the error type, the server may wish to display the error to the user. */
public class SlimeReportError implements CommandData {
	public static final UUID COMMAND_UUID = UUID.fromString("00000008-445e-4484-bc3d-f0c696a3080c");
	public static final long FLAGS = 1;

	/**  An identifier for the error */
	public UUID error_type;

	@Override
	public UUID getCommandUUID(){
		return SlimeReportError.COMMAND_UUID;
	}

	@Override
	public void get(SByteBuffer buf){
		error_type = buf.getUUID();
	}

	@Override
	public void put(SByteBuffer buf){
		buf.putUUID(error_type);
	}

	public static SlimeReportError get_s(SByteBuffer buf){
		SlimeReportError f = new SlimeReportError();
		f.get(buf);
		return f;
	}
}