// This file is automatically generated, please do not touch

package slime.base.proto.autogen;


import slime.base.proto.SByteBuffer;
import slime.base.proto.types.*;
import slime.base.proto.autogen.*;
import slime.base.proto.Util;
import java.util.UUID;

/**  This is the first packet sent by the client. This is intended for the server to detect endianness mode and ensure it is decoding packets correctly. */
public class SlimeHandshakeInit implements CommandData {
	public static final UUID COMMAND_UUID = UUID.fromString("00000001-445e-4484-bc3d-f0c696a3080c");
	public static final long FLAGS = 1;

	/**  Must be set to SLIME_HANDSHAKE_INIT_UUID */
	public UUID magic_uuid;

	/**  Must be set to SLIME_HANDSHAKE_INIT_INT */
	public long magic_int;

	/**  Must be set to SLIME_HANDSHAKE_INIT_SHORT */
	public int magic_short;

	/**  Must be set to SLIME_HANDSHAKE_INIT_BYTE */
	public short magic_byte;

	@Override
	public UUID getCommandUUID(){
		return SlimeHandshakeInit.COMMAND_UUID;
	}

	@Override
	public void get(SByteBuffer buf){
		magic_uuid = buf.getUUID();
		magic_int = buf.getU32();
		magic_short = buf.getU16();
		magic_byte = buf.getU8();
	}

	@Override
	public void put(SByteBuffer buf){
		buf.putUUID(magic_uuid);
		buf.putU32(magic_int);
		buf.putU16(magic_short);
		buf.putU8(magic_byte);
	}

	public static SlimeHandshakeInit get_s(SByteBuffer buf){
		SlimeHandshakeInit f = new SlimeHandshakeInit();
		f.get(buf);
		return f;
	}
}