// This file is automatically generated, please do not touch

package slime.base.proto.autogen;


import slime.base.proto.SByteBuffer;
import slime.base.proto.types.*;
import slime.base.proto.autogen.*;
import slime.base.proto.Util;
import java.util.UUID;

/**  */
public class SlimePacketAcknowledgment implements CommandData {
	public static final UUID COMMAND_UUID = UUID.fromString("00000006-445e-4484-bc3d-f0c696a3080c");
	public static final long FLAGS = 3;

	/**  */
	public int packet_number;

	@Override
	public UUID getCommandUUID(){
		return SlimePacketAcknowledgment.COMMAND_UUID;
	}

	@Override
	public void get(SByteBuffer buf){
		packet_number = buf.getU16();
	}

	@Override
	public void put(SByteBuffer buf){
		buf.putU16(packet_number);
	}

	public static SlimePacketAcknowledgment get_s(SByteBuffer buf){
		SlimePacketAcknowledgment f = new SlimePacketAcknowledgment();
		f.get(buf);
		return f;
	}
}