// This file is automatically generated, please do not touch

package slime.base.proto.autogen;


import slime.base.proto.SByteBuffer;
import slime.base.proto.types.*;
import slime.base.proto.autogen.*;
import slime.base.proto.Util;
import java.util.UUID;

/**  Upon receiving such a descriptor, the server must respond acknowledging that the descriptor was successfully received: */
public class SlimeCommandDescriptorResponse implements CommandData {
	public static final UUID COMMAND_UUID = UUID.fromString("00000005-445e-4484-bc3d-f0c696a3080c");
	public static final long FLAGS = 2;

	/**  The handle value which the client sent */
	public Handle handle;

	/**  Status of the descriptor */
	public long status;

	@Override
	public UUID getCommandUUID(){
		return SlimeCommandDescriptorResponse.COMMAND_UUID;
	}

	@Override
	public void get(SByteBuffer buf){
		handle = buf.getHandle();
		status = buf.getU32();
	}

	@Override
	public void put(SByteBuffer buf){
		buf.putHandle(handle);
		buf.putU32(status);
	}

	public static SlimeCommandDescriptorResponse get_s(SByteBuffer buf){
		SlimeCommandDescriptorResponse f = new SlimeCommandDescriptorResponse();
		f.get(buf);
		return f;
	}
}