// This file is automatically generated, please do not touch

package slime.base.proto.autogen;


import slime.base.proto.SByteBuffer;
import slime.base.proto.types.*;
import slime.base.proto.autogen.*;
import slime.base.proto.Util;
import java.util.UUID;

/**  This command declares that no more command descriptors will be sent, and that it's safe to make the handle->command mapping immutable (unless a handshake packet is resent) (TODO) */
public class SlimeDescriptorFinalize implements CommandData {
	public static final UUID COMMAND_UUID = UUID.fromString("00000009-445e-4484-bc3d-f0c696a3080c");
	public static final long FLAGS = 1;

	@Override
	public UUID getCommandUUID(){
		return SlimeDescriptorFinalize.COMMAND_UUID;
	}

	@Override
	public void get(SByteBuffer buf){
	}

	@Override
	public void put(SByteBuffer buf){
	}

	public static SlimeDescriptorFinalize get_s(SByteBuffer buf){
		SlimeDescriptorFinalize f = new SlimeDescriptorFinalize();
		f.get(buf);
		return f;
	}
}