// This file is automatically generated, please do not touch

package slime.base.proto.autogen;


import slime.base.proto.SByteBuffer;
import slime.base.proto.types.*;
import slime.base.proto.autogen.*;
import slime.base.proto.Util;
import java.util.UUID;

/**  Sent by the server in response to `SlimeHandshakeInit` */
public class SlimeHandshakeInitResponse implements CommandData {
	public static final UUID COMMAND_UUID = UUID.fromString("00000002-445e-4484-bc3d-f0c696a3080c");
	public static final long FLAGS = 2;

	/**  Must be set to SLIME_HANDSHAKE_RESPONSE_MAGIC */
	public long magic;

	@Override
	public UUID getCommandUUID(){
		return SlimeHandshakeInitResponse.COMMAND_UUID;
	}

	@Override
	public void get(SByteBuffer buf){
		magic = buf.getU32();
	}

	@Override
	public void put(SByteBuffer buf){
		buf.putU32(magic);
	}

	public static SlimeHandshakeInitResponse get_s(SByteBuffer buf){
		SlimeHandshakeInitResponse f = new SlimeHandshakeInitResponse();
		f.get(buf);
		return f;
	}
}